# Home directory
path: /home/borealis/Documents/study/Netology/dll/final_project_dll/Real-Time-Detection/data/processed

# Samples
train: images/train
val: images/val

# Samples labels
train_labels: labels/train
val_labels: labels/val

# Classes
names:
  0: person
  1: car
  2: truck
  3: bus
  4: train
  5: motorcycle
  6: bicycle
  7: rider

# Count classes
nc: 8
